sudo: false
language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm
script:
  - npm run build
cache:
  directories:
    - node_modules/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  fqdn: reactackle.braincrumbs.io
  on:
    branch: master
